In [2]:
# First setup client
from pprint import pprint

from src.client import ExchangeClient
from src.request_utils import load_private_key_from_file

In [3]:
from src.params import *

prod_private_key = load_private_key_from_file(KALSHI_KEY)
exchange_client = ExchangeClient(exchange_api_base=PROD_API_BASE, key_id = API_ID, private_key = prod_private_key)

# first we will check on the exchange status to confirm you are properly connected...
print(exchange_client.get_exchange_status())

{'exchange_active': True, 'trading_active': True}


In [8]:
# First get the trading prices for the deep-blue bet
response = exchange_client.get_markets(series_ticker="KXSTATEDEEPDJT")
response

{'markets': [{'ticker': 'KXSTATEDEEPDJT-24-R',
   'event_ticker': 'KXSTATEDEEPDJT-24-R',
   'market_type': 'binary',
   'title': 'Will Trump win a deep blue state?',
   'subtitle': '',
   'yes_sub_title': 'Yes',
   'no_sub_title': 'Yes',
   'open_time': '2024-10-25T14:00:00Z',
   'close_time': '2025-11-05T15:00:00Z',
   'expected_expiration_time': '2025-01-07T15:00:00Z',
   'expiration_time': '2025-11-05T15:00:00Z',
   'latest_expiration_time': '2025-11-05T15:00:00Z',
   'settlement_timer_seconds': 300,
   'status': 'active',
   'response_price_units': 'usd_cent',
   'notional_value': 100,
   'tick_size': 1,
   'yes_bid': 21,
   'yes_ask': 24,
   'no_bid': 76,
   'no_ask': 79,
   'last_price': 24,
   'previous_yes_bid': 20,
   'previous_yes_ask': 23,
   'previous_price': 23,
   'volume': 1218859,
   'volume_24h': 490210,
   'liquidity': 204415702,
   'open_interest': 722794,
   'result': '',
   'can_close_early': True,
   'expiration_value': '',
   'category': 'Elections',
   'risk_lim

In [10]:
# TODO Use this to get the data for the other states
response = exchange_client.get_markets(series_ticker="PRESPARTYCA")
response

{'markets': [{'ticker': 'PRESPARTYCA-24-R',
   'event_ticker': 'PRESPARTYCA-24',
   'market_type': 'binary',
   'title': 'Will the Republican party win California in the presidential election?',
   'subtitle': ':: or another Republican',
   'yes_sub_title': 'Donald Trump',
   'no_sub_title': 'Donald Trump',
   'open_time': '2024-10-11T14:00:00Z',
   'close_time': '2025-11-05T15:00:00Z',
   'expected_expiration_time': '2025-01-07T15:00:00Z',
   'expiration_time': '2025-11-05T15:00:00Z',
   'latest_expiration_time': '2025-11-05T15:00:00Z',
   'settlement_timer_seconds': 14,
   'status': 'active',
   'response_price_units': 'usd_cent',
   'notional_value': 100,
   'tick_size': 1,
   'yes_bid': 3,
   'yes_ask': 4,
   'no_bid': 96,
   'no_ask': 97,
   'last_price': 4,
   'previous_yes_bid': 2,
   'previous_yes_ask': 4,
   'previous_price': 4,
   'volume': 888325,
   'volume_24h': 250975,
   'liquidity': 460962894,
   'open_interest': 622267,
   'result': '',
   'can_close_early': True,
   '

In [8]:
# Solver for the linear program
import numpy as np
from scipy.optimize import linprog

from src.np_utils import enumerate_binary_inputs

def make_event_matrix(n: int, probs: np.ndarray, fix_most_likely: int=0) -> np.ndarray:
    # last event is product of first n-1 events
    varying_events = n - 1 - fix_most_likely
    event_mat = np.empty((2 ** varying_events, n), dtype=np.int8)
    event_mat[:, :varying_events] = enumerate_binary_inputs(varying_events, dtype=event_mat.dtype)
    event_mat[:, varying_events:-1] = 1
    event_mat[:, -1] = np.prod(event_mat[:, :-1], axis=1)
    # Now rearrange based on probabilities
    # varying_events...n-1 are the most likely
    # 0...varying_events-1 are the least likely
    # Make a permutation to sort the columns
    if fix_most_likely > 0:
        prob_argsort = np.argsort(probs)
        col_inds = np.argsort(prob_argsort)
        event_mat[:, :-1] = event_mat[:, col_inds]
    
    return event_mat

def make_bound_matrix(event_matrix: np.ndarray, cost_weights: np.ndarray) -> np.ndarray:
    n = event_matrix.shape[1]
    # Result should be 2^(n-1) x 2n
    bound_matrix = np.empty((event_matrix.shape[0], 2*n), dtype=cost_weights.dtype)
    bound_matrix[:, :n] = event_matrix - cost_weights[None, :n]
    bound_matrix[:, n:] = 1 - event_matrix - cost_weights[None, n:]
    return bound_matrix




In [ ]:
# Test things out first
n_events = 4
min_profit_rate=0.625
# cost_weights = np.full(n_events * 2, 0.3, dtype=np.float16)
cost_weights = np.array([0.1, 0.1, 0.1, 0.5, 0.9, 0.9, 0.9, 0.5], dtype=np.float16) # Test for n_events = 4
event_matrix = make_event_matrix(n_events)
bound_matrix = make_bound_matrix(event_matrix, cost_weights)

In [100]:
print(cost_weights)
print(event_matrix)
print(bound_matrix)

[0.1 0.1 0.1 0.5 0.9 0.9 0.9 0.5]
[[0 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 1 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 1 0 0]
 [1 1 1 1]]
[[-0.1        -0.1        -0.1        -0.5         0.10000002  0.10000002
   0.10000002  0.5       ]
 [-0.1        -0.1         0.9        -0.5         0.10000002  0.10000002
  -0.9         0.5       ]
 [-0.1         0.9        -0.1        -0.5         0.10000002 -0.9
   0.10000002  0.5       ]
 [-0.1         0.9         0.9        -0.5         0.10000002 -0.9
  -0.9         0.5       ]
 [ 0.9        -0.1        -0.1        -0.5        -0.9         0.10000002
   0.10000002  0.5       ]
 [ 0.9        -0.1         0.9        -0.5        -0.9         0.10000002
  -0.9         0.5       ]
 [ 0.9         0.9        -0.1        -0.5        -0.9        -0.9
   0.10000002  0.5       ]
 [ 0.9         0.9         0.9         0.5        -0.9        -0.9
  -0.9        -0.5       ]]


In [101]:
res = linprog(
    cost_weights, 
    A_ub=-bound_matrix, # Negative because this computes negative profit
    b_ub=np.full(bound_matrix.shape[0], fill_value=-min_profit_rate), # Negative because we want to lower bound profit
    A_eq=cost_weights[None, :],
    b_eq=np.array([1], dtype=cost_weights.dtype),  # We are constrained to spending $1
    bounds=(0, None)
)

res.message

'Optimization terminated successfully. (HiGHS Status 7: Optimal)'

In [102]:
yes = res.x[:n_events]
no = res.x[n_events:]

print(yes)
print(no)
print(res.fun)

[0.06249999 0.         1.56250005 0.        ]
[ 0.06249999 -0.          0.          1.56250001]
0.9999999999999999


In [103]:
# Min profit achieved by solution
guaranteed_profit_rate = np.min(bound_matrix @ res.x) / (cost_weights @ res.x)
guaranteed_profit_rate

np.float64(0.6250000000000001)

In [28]:
# Now we test things out for real
DEEP_BLUE_STATES = [
    "CA",
    "CO",
    "CT",
    "DE",
    "HI",
    "IL",
    "MD",
    "MA",
    "NJ",
    "NM",
    "NY",
    "OR",
    "RI",
    "VT",
    "VA",
    "WA",
]
DEEP_BLUE_STATE_TICKERS = [f"PRESPARTY{abbr}-24" for abbr in DEEP_BLUE_STATES]
DEEP_BLUE_TICKER = "KXSTATEDEEPDJT-24-R"

In [29]:
# Get the price for the deep blue bet
response = exchange_client.get_markets(tickers=DEEP_BLUE_TICKER)
# This is the price to buy "No, DJT does not win any deep blue states"
db_kam = response['markets'][0]['no_ask'] / 100
# This is the price to buy "Yes, DJT does win some deep blue states"
db_trump = response['markets'][0]['yes_ask'] / 100

pprint(response)
db_kam, db_trump

{'cursor': '',
 'markets': [{'can_close_early': True,
              'category': 'Elections',
              'close_time': '2025-11-05T15:00:00Z',
              'event_ticker': 'KXSTATEDEEPDJT-24-R',
              'expected_expiration_time': '2025-01-07T15:00:00Z',
              'expiration_time': '2025-11-05T15:00:00Z',
              'expiration_value': '',
              'last_price': 24,
              'latest_expiration_time': '2025-11-05T15:00:00Z',
              'liquidity': 203951240,
              'market_type': 'binary',
              'no_ask': 80,
              'no_bid': 76,
              'no_sub_title': 'Yes',
              'notional_value': 100,
              'open_interest': 730324,
              'open_time': '2024-10-25T14:00:00Z',
              'previous_price': 22,
              'previous_yes_ask': 22,
              'previous_yes_bid': 20,
              'response_price_units': 'usd_cent',
              'result': '',
              'risk_limit_cents': 0,
              'rules_

(0.8, 0.24)

In [30]:
# Get the price for the deep blue bet
kam_state_prices = []
trump_state_prices = []
for state, ticker in zip(DEEP_BLUE_STATES, DEEP_BLUE_STATE_TICKERS):
    response_d = exchange_client.get_markets(tickers=f"{ticker}-D")
    response_r = exchange_client.get_markets(tickers=f"{ticker}-R")
    # This is the price to buy "Yes, Kamala Harris wins this state"
    kam_price = min(response_d['markets'][0]['yes_ask'] / 100, response_r['markets'][0]['no_ask'] / 100)
    # This is the price to buy "Yes, DJT does win some deep blue states"
    trump_price = min(response_d['markets'][0]['no_ask'] / 100, response_r['markets'][0]['yes_ask'] / 100)

    # pprint(response)
    kam_state_prices.append(kam_price)
    trump_state_prices.append(trump_price)

for state, kam_price, trump_price in zip(DEEP_BLUE_STATES, kam_state_prices, trump_state_prices):
    print(f"{state}: Kamala Harris: {kam_price} Trump: {trump_price}")



CA: Kamala Harris: 0.97 Trump: 0.04
CO: Kamala Harris: 0.95 Trump: 0.06
CT: Kamala Harris: 0.97 Trump: 0.05
DE: Kamala Harris: 0.97 Trump: 0.04
HI: Kamala Harris: 0.96 Trump: 0.06
IL: Kamala Harris: 0.96 Trump: 0.06
MD: Kamala Harris: 0.97 Trump: 0.05
MA: Kamala Harris: 0.98 Trump: 0.04
NJ: Kamala Harris: 0.95 Trump: 0.07
NM: Kamala Harris: 0.9 Trump: 0.11
NY: Kamala Harris: 0.96 Trump: 0.05
OR: Kamala Harris: 0.96 Trump: 0.06
RI: Kamala Harris: 0.97 Trump: 0.05
VT: Kamala Harris: 0.98 Trump: 0.04
VA: Kamala Harris: 0.88 Trump: 0.13
WA: Kamala Harris: 0.97 Trump: 0.04


In [81]:
cost_weights = np.array(kam_state_prices + [db_kam] + trump_state_prices + [db_trump], dtype=np.float16)
# Alternatively we 
# cost_weights = np.array(kam_state_prices + [db_kam], dtype=np.float16)
# cost_weights = np.concatenate([cost_weights, 1- cost_weights])

assert len(cost_weights) % 2 == 0
n_events = len(cost_weights) // 2
print(f"Number of events: {n_events}")

# What if I edit the cost weights for deep blue
# cost_weights[n_events] = 0.5
# cost_weights[-1] = 0.5
print(f"Cost Weights: {cost_weights}")

min_profit_rate=0.0306
print(f"Min profit rate: {min_profit_rate}")

event_matrix = make_event_matrix(n_events, fix_most_likely=3, probs=cost_weights[:n_events-1])
bound_matrix = make_bound_matrix(event_matrix, cost_weights)
print(f"Event Matrix Shape: {event_matrix.shape}")
print(f"Event Matrix First Rows: {event_matrix[:10]}")
print(f"Event Matrix Dtype: {event_matrix.dtype}")
print(f"Bound Matrix Shape: {bound_matrix.shape}")
print(f"Bound Matrix First Rows: {bound_matrix[:10]}")
print(f"Bound Matrix Dtype: {bound_matrix.dtype}")

Number of events: 17
Cost Weights: [0.97 0.95 0.97 0.97 0.96 0.96 0.97 0.98 0.95 0.9  0.96 0.96 0.97 0.98
 0.88 0.97 0.8  0.04 0.06 0.05 0.04 0.06 0.06 0.05 0.04 0.07 0.11 0.05
 0.06 0.05 0.04 0.13 0.04 0.24]
Min profit rate: 0.0306
Event Matrix Shape: (8192, 17)
Event Matrix First Rows: [[0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0]
 [0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0]]
Event Matrix Dtype: int8
Bound Matrix Shape: (8192, 34)
Bound Matrix First Rows: [[-0.97    -0.95    -0.97    -0.97    -0.96    -0.96    -0.97     0.02002
  -0.95    -0.9     -0.96    -0.96    -0.97     0.02002 -0.88     0.02979
  -0.8      0.96     0.94     0.95     0.96     0.94     0.94     0.95
  -0.04     0.93     0.89     0.95     0

In [82]:
res = linprog(
    cost_weights, 
    A_ub=-bound_matrix, # Negative because this computes negative profit
    b_ub=np.full(bound_matrix.shape[0], fill_value=-min_profit_rate), # Negative because we want to lower bound profit
    A_eq=cost_weights[None, :],
    b_eq=np.array([1], dtype=cost_weights.dtype),  # We are constrained to spending $1, this will force us to do something
    bounds=(0, None),
    method="highs"
)

res.message

'Optimization terminated successfully. (HiGHS Status 7: Optimal)'

In [83]:
yes = res.x[:n_events]
no = res.x[n_events:]

print(yes)
print(cost_weights[:n_events-1])

print(no)
print(cost_weights[n_events+1:-1])

print(res.fun)
print(np.argsort(-cost_weights[:n_events-1]))

[-0.          0.          0.         -0.          0.00194145  0.
  0.          0.          0.          0.         -0.          0.
  0.          0.          0.          1.02865855  0.        ]
[0.97 0.95 0.97 0.97 0.96 0.96 0.97 0.98 0.95 0.9  0.96 0.96 0.97 0.98
 0.88 0.97]
[ 0.          0.          0.          0.          0.00194157  0.
  0.          0.          0.          0.          0.         -0.
  0.          0.          0.          0.          0.        ]
[0.06 0.05 0.04 0.06 0.06 0.05 0.04 0.07 0.11 0.05 0.06 0.05 0.04 0.13
 0.04]
1.0
[ 7 13  0  2  3  6 12 15  4  5 10 11  1  8  9 14]


In [56]:
# Min profit achieved by solution
profit_rates = (bound_matrix @ res.x.astype(np.float32)) / (cost_weights @ res.x)
guaranteed_profit_rate = np.min(profit_rates)
profit_rate_minimizer = np.argmin(profit_rates)
print(guaranteed_profit_rate)
print(event_matrix[profit_rate_minimizer])


np.float64(0.03009999915957451)

In [4]:
DEEP_RED_STATES = [
    "AL",
    "AK",
    "AR",
    "ID",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "MS",
    "MO",
    "MT",
    "NE",
    "ND",
    "OH",
    "OK",
    "SC",
    "SD",
    "TN",
    "UT",
    "WV",
    "WY",
]
DEEP_RED_STATE_TICKERS = [f"PRESPARTY{abbr}-24" for abbr in DEEP_RED_STATES]
DEEP_RED_TICKER = "KXSTATEDEEPKH-24-D"

In [5]:
# Get the price for the deep red bet
response = exchange_client.get_markets(tickers=DEEP_RED_TICKER)
# This is the price to buy "No, KH does not win any deep red states"
dr_trump = response['markets'][0]['no_ask'] / 100
# This is the price to buy "Yes, KH does win some deep red states"
dr_kh = response['markets'][0]['yes_ask'] / 100

pprint(response)
dr_kh, dr_trump

{'cursor': '',
 'markets': [{'can_close_early': True,
              'category': 'Elections',
              'close_time': '2025-11-05T15:00:00Z',
              'event_ticker': 'KXSTATEDEEPKH-24-D',
              'expected_expiration_time': '2025-01-07T15:00:00Z',
              'expiration_time': '2025-11-05T15:00:00Z',
              'expiration_value': '',
              'last_price': 24,
              'latest_expiration_time': '2025-11-05T15:00:00Z',
              'liquidity': 150007488,
              'market_type': 'binary',
              'no_ask': 76,
              'no_bid': 72,
              'no_sub_title': 'Yes',
              'notional_value': 100,
              'open_interest': 188275,
              'open_time': '2024-10-25T14:00:00Z',
              'previous_price': 31,
              'previous_yes_ask': 31,
              'previous_yes_bid': 24,
              'response_price_units': 'usd_cent',
              'result': '',
              'risk_limit_cents': 0,
              'rules_p

(0.28, 0.76)

In [6]:
# Get the price for the deep blue bet
kam_state_prices = []
trump_state_prices = []
for state, ticker in zip(DEEP_RED_STATES, DEEP_RED_STATE_TICKERS):
    response_d = exchange_client.get_markets(tickers=f"{ticker}-D")
    response_r = exchange_client.get_markets(tickers=f"{ticker}-R")
    # This is the price to buy "Yes, Trump wins this state"
    trump_price = min(response_r['markets'][0]['yes_ask'] / 100, response_d['markets'][0]['no_ask'] / 100)
    # This is the price to buy "No, Trump does not win this state"
    kam_price = min(response_r['markets'][0]['no_ask'] / 100, response_d['markets'][0]['yes_ask'] / 100)

    # pprint(response)
    kam_state_prices.append(kam_price)
    trump_state_prices.append(trump_price)

for state, kam_price, trump_price in zip(DEEP_RED_STATES, kam_state_prices, trump_state_prices):
    print(f"{state}: Kamala Harris: {kam_price} Trump: {trump_price}")



AL: Kamala Harris: 0.04 Trump: 1.0
AK: Kamala Harris: 0.09 Trump: 0.92
AR: Kamala Harris: 0.03 Trump: 1.0
ID: Kamala Harris: 0.03 Trump: 0.98
IN: Kamala Harris: 0.05 Trump: 0.97
IA: Kamala Harris: 0.2 Trump: 0.82
KS: Kamala Harris: 0.07 Trump: 0.95
KY: Kamala Harris: 0.04 Trump: 0.99
LA: Kamala Harris: 0.06 Trump: 0.98
MS: Kamala Harris: 0.05 Trump: 0.97
MO: Kamala Harris: 0.05 Trump: 0.97
MT: Kamala Harris: 0.05 Trump: 0.98
NE: Kamala Harris: 0.07 Trump: 0.96
ND: Kamala Harris: 0.03 Trump: 0.99
OH: Kamala Harris: 0.09 Trump: 0.92
OK: Kamala Harris: 0.04 Trump: 0.98
SC: Kamala Harris: 0.05 Trump: 0.97
SD: Kamala Harris: 0.03 Trump: 0.98
TN: Kamala Harris: 0.05 Trump: 0.97
UT: Kamala Harris: 0.05 Trump: 0.97
WV: Kamala Harris: 0.03 Trump: 0.98
WY: Kamala Harris: 0.04 Trump: 0.98


In [24]:
import numpy as np

cost_weights = np.array(trump_state_prices + [dr_trump] + kam_state_prices + [dr_kh], dtype=np.float16)
# Alternatively we 
# cost_weights = np.array(kam_state_prices + [db_kam], dtype=np.float16)
# cost_weights = np.concatenate([cost_weights, 1- cost_weights])

assert len(cost_weights) % 2 == 0
n_events = len(cost_weights) // 2
print(f"Number of events: {n_events}")

# What if I edit the cost weights for deep blue
# cost_weights[n_events] = 0.5
# cost_weights[-1] = 0.5
print(f"Cost Weights: {cost_weights}")

min_profit_rate=0.02
print(f"Min profit rate: {min_profit_rate}")

event_matrix = make_event_matrix(n_events, probs=cost_weights[:n_events-1], fix_most_likely=7)
bound_matrix = make_bound_matrix(event_matrix, cost_weights)
print(f"Event Matrix Shape: {event_matrix.shape}")
print(f"Event Matrix First Rows: {event_matrix[:10]}")
print(f"Event Matrix Dtype: {event_matrix.dtype}")
print(f"Bound Matrix Shape: {bound_matrix.shape}")
print(f"Bound Matrix First Rows: {bound_matrix[:10]}")
print(f"Bound Matrix Dtype: {bound_matrix.dtype}")

Number of events: 23
Cost Weights: [1.   0.92 1.   0.98 0.97 0.82 0.95 0.99 0.98 0.97 0.97 0.98 0.96 0.99
 0.92 0.98 0.97 0.98 0.97 0.97 0.98 0.98 0.76 0.04 0.09 0.03 0.03 0.05
 0.2  0.07 0.04 0.06 0.05 0.05 0.05 0.07 0.03 0.09 0.04 0.05 0.03 0.05
 0.05 0.03 0.04 0.28]
Min profit rate: 0.02
Event Matrix Shape: (32768, 23)
Event Matrix First Rows: [[1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0]
 [1 0 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0]
 [1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0]
 [1 0 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0]
 [1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0]
 [1 0 1 1 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0]
 [1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0]
 [1 0 1 1 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 1 0]
 [1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0]
 [1 0 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 1 0 0]]
Event Matrix Dtype: int8
Bound Matrix Shape: (32768, 46)
Bound Matrix First Rows: [[ 0.       -0.92      0.        0.02002  -0.97     -0.82     -0.95
   0.00976

In [25]:
from scipy.optimize import linprog

res = linprog(
    cost_weights, 
    A_ub=-bound_matrix, # Negative because this computes negative profit
    b_ub=np.full(bound_matrix.shape[0], fill_value=-min_profit_rate), # Negative because we want to lower bound profit
    A_eq=cost_weights[None, :],
    b_eq=np.array([1], dtype=cost_weights.dtype),  # We are constrained to spending $1, this will force us to do something
    bounds=(0, None),
    method="highs"
)

res.message

'Optimization terminated successfully. (HiGHS Status 7: Optimal)'

In [27]:
yes = res.x[:n_events]
no = res.x[n_events:]

print(yes)
print(no)
print(res.fun)
print(cost_weights[:n_events-1])

[ 0.          0.          0.          0.97904762  0.         -0.
  0.          0.04095238  0.         -0.         -0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.        ]
[ 0.  0.  0.  0. -0.  0. -0.  0.  0.  0.  0. -0.  0.  0.  0. -0.  0. -0.
 -0. -0.  0. -0.  0.]
1.0
[1.   0.92 1.   0.98 0.97 0.82 0.95 0.99 0.98 0.97 0.97 0.98 0.96 0.99
 0.92 0.98 0.97 0.98 0.97 0.97 0.98 0.98]
